### ISSUE TITLE
Null Reference Exception when adding new [BonaDataEditor] to a scriptable object

### ISSUE THREAD

**Issue by KOKOStern** [bonahona/BonaDataEditor#1]
There are 12 Null Exceptions exactly and they come from different places. It always gets to Editor.get_serializedObject, but comes from multiple places:

`UnityEditor.TransformInspector.OnEnable () (at C:/buildslave/unity/build/Editor/Mono/Inspector/TransformInspector.cs:23)`
`UnityEditor.GameObjectInspector.OnEnable () (at C:/buildslave/unity/build/Editor/Mono/Inspector/GameObjectInspector.cs:121)`

First one full stack trace:

`NullReferenceException: (null)
UnityEditor.SerializedObject..ctor (UnityEngine.Object[] objs, UnityEngine.Object context) (at C:/buildslave/unity/build/Editor/Mono/SerializedObject.cs:26)
UnityEditor.Editor.GetSerializedObjectInternal () (at C:/buildslave/unity/build/Editor/Mono/Inspector/Editor.cs:516)
UnityEditor.Editor.get_serializedObject () (at C:/buildslave/unity/build/Editor/Mono/Inspector/Editor.cs:433)
UnityEditor.Collider3DEditorBase.OnEnable () (at C:/buildslave/unity/build/Editor/Mono/Inspector/Collider3DEditorBase.cs:16)
UnityEditor.BoxColliderEditor.OnEnable () (at C:/buildslave/unity/build/Editor/Mono/Inspector/BoxColliderEditor.cs:20)
`

Good luck!

**Comment by bonahona** [comment]
Managed to recreate the error locally. Probably caused by some trailing editors after their sources has been removed one way or another as some editors seems to not be cleaned up properly.
